{
    'name': 'Department Helpdesk',
    'version': '19.0.1.0.0',
    'summary': 'Adds Department field to Helpdesk Tickets',
    'author': 'Nithya',
    'license': 'LGPL-3',
    'category': 'Helpdesk',
    'depends': ["base",
                'hr',
                'purchase',
                'account',
                'estate_management',
                'custom_inventory',
                "helpdesk_mgmt",
                "helpdesk_type",
                "helpdesk_mgmt_sla",
                "helpdesk_type_sla", "project", "web_timeline", "project_main_mgmt",
                ],
    'data': [
        "security/security_groups.xml",
        'security/ir.model.access.csv',
        'data/cron.xml',
        'data/facility_department.xml',
        'data/department_data.xml',
        'views/helpdesk_ticket_views.xml',
        # 'views/external_ticketing_views.xml',
        "views/External_ticketing_separate.xml",
        # 'views/helpdesk_department_views.xml',
        'views/helpdesk_ticket_it_incident_views.xml',
        'views/it_asset_views.xml',
        'views/hr_request_views.xml',
        'data/helpdesk_stage_inherit.xml',
    ],
    'installable': True,
    'application': False,
}
