{
    "name": "Project Main Mgmt",
    "version": "1.0",
    "category": "Project",
    "summary": "Create a Smart Buttons in a Project module",
    "author": "Kiran",
    "description": """
            - Smart buttons
            """,
    "depends": ['project', 'mail', 'expected_date', 'project_category', 'project_hierarchy_management', 'analytic',
                'hr_timesheet'
                ],
    "data": [
        'security/project_rules.xml',
        'security/ir.model.access.csv',
        'data/project_followers_subtypes.xml',
        'data/project_followers_governance_access.xml',
        'data/project_deadline_subtype.xml',
        'data/mail_templates.xml',
        'data/project_task_email_template.xml',
        'data/sla_subtask_template.xml',
        'data/sla_mail_template.xml',
        'data/sla_user_story_templates.xml',
        'data/sla_epic_template.xml',
        'data/sla_backlog_template.xml',
        'data/sla_project_template.xml',
        'data/work_reminder_template.xml',
        'data/governance_review_reminder.xml',
        'data/approver_add_remove_template.xml',
        'data/cron.xml',
        'views/epic_views.xml',
        'views/product_backlog_views.xml',
        'views/subtask_views.xml',
        'views/user_story_views.xml',
        'views/project_task_view.xml',
        'views/project_task_sla_views.xml',
        'views/task_kanban_inherit.xml',
        'views/backlog_type_master.xml',
        'views/project_project_view.xml',
        'views/project_form_sla.xml',
        'views/project_sprint_views.xml',
        'views/progress_config_views.xml',
        'views/subtask_sla_kanban_badge.xml',
        'views/project_user_story_sla_views.xml',
        'views/project_epic_sla_views.xml',
        'views/project_product_backlog_sla_views.xml',
        'views/hide_planned_date.xml',
        'views/subtask_actions.xml',
        'views/subtask_menu.xml',

    ],
    'assets': {
        'web.assets_backend': [
            'project_main_mgmt/static/src/css/progress_bar.css',
            'project_main_mgmt/static/src/css/style.css',
            'project_main_mgmt/static/src/js/progress_color.js',
            'project_main_mgmt/static/src/xml/color_only.xml',
        ],
    },
    "installable": True,
    "application": False,
}
